"use strict";

const config = {
  tenant: {
    id: "COMPANY A",
    name: "Company A",
  },
  badge: {
    lastSeconds: 3000,
  },
  cocodoc: {
    doc_id: "dummydocnotallowed",
    name: "",
    prjid: "dummydocnotallowed",
    owner: "dummydocnotallowed",
    readonly: false,
  },
  oss: {
    cocopad_bucket_name: "cocopad",
  },
  vault: {
    bucket: "vts",
  },
  product: {
    url: "https://colobod.com",
    basedir: "",
  },
  ws_server: {
    endpoint: { label: "LOCAL", url: "ws://localhost:5008/grume/wsquux" },
    endpoint_lzj: {
      label: "LZJ",
      url: "wss://liuzijin.com/clbdapi/grume/wsquux",
    },
    endpoint_local: { label: "LOCAL", url: "ws://localhost:5008/grume/wsquux" },
  },
  frontend: {
    url: "https://mlib.liuzijin.com/frontend",
    url_remote: "https://mlib.liuzijin.com/frontend",
    url_local: "http://localhost:8087",
  },
  cos: {
    region: "ap-nanjing",
    bucket: "nanjing1-1255349658",
    domain: "cos.ap-nanjing.myqcloud.com",
    reverseproxy: "mlib.liuzijin.com",
  },
  ui: {
    boundingrect_padding: 10,
  },
  node: {
    image: {
      resizable: true,
    },
    text: {
      edittable: true,
      resizable: false,
      droppable: false,
      style: {
        width: "200",
        height: "30",
        display: "block",
        color: "black",
        "background-color": "transparent",
        padding: "0px",
        margin: "0px",
        overflow: "show",
        position: "absolute",
      },
      inner: {
        content: "单行文字",
        style: {
          display: "block",
          padding: "0px",
          "white-space": "nowrap",
          "font-size": "18px",
          color: "black",
          width: "fit-content",
          height: "fit-content",
          "z-index": 1,
        },
      },
    },
    yellowtip: {
      edittable: true,
      resizable: true,
      droppable: true,
      defaultTip: "tip",
      minWidth: 50,
      minHeight: 50, //resize的最小高度和宽度
      style: {
        width: "160",
        height: "160",
        display: "flex",
        padding: "2px",
        margin: "0px",
        overflow: "show",
        color: "black",
        "background-color": "transparent",
        position: "absolute",
      },
      inner: {
        content: "",
        style: {
          display: "flex",
          "font-size": "18px",
          color: "black",
          position: "absolute",
          width: "100%",
          height: "100%",
          "z-index": 1,
          "justify-content": "center",
          "align-items": "center",
        },
      },
    },
    comment: {
      edittable: true,
      resizable: true,
      droppable: false,
      defaultTip: "comment",
      defaultColor: "#93C47D99",
      minWidth: 150,
      minHeight: 20, //resize的最小高度和宽度
      style: {
        width: "160",
        height: "50",
        display: "flex",
        padding: "0px",
        margin: "0px",
        overflow: "scroll",
        color: "black",
        "background-color": "transparent",
        position: "absolute",
      },
      inner: {
        content: "",
        style: {
          display: "flex",
          "font-size": "10px",
          color: "black",
          "font-style": "italic",
          position: "absolute",
          width: "100%",
          height: "100%",
          "z-index": 1,
          "justify-content": "flex-start",
          "align-items": "flex-start",
          "padding-left": "15px",
        },
      },
    },
    textblock: {
      edittable: true,
      resizable: true,
      droppable: true,
      defaultTip: "tip",
      minWidth: 30,
      minHeight: 30,
      customshape: true,
      style: {
        width: "240",
        height: "40",
        display: "flex",
        padding: "2px",
        margin: "0px",
        overflow: "show",
        "background-color": "#FFFFFF",
        "border-color": "#333333",
        "border-width": "1px",
        "border-style": "solid",
        "border-radius": "5px",
        position: "absolute",
      },
      inner: {
        content: "",
        style: {
          display: "flex",
          padding: "0px",
          "font-size": "18px",
          color: "black",
          width: "100%",
          height: "100%",
          "z-index": 1,
          "justify-content": "flex-start",
          "align-items": "center",
        },
      },
    },
    richtext: {
      edittable: false,
      resizable: true,
      droppable: true,
      minWidth: 200,
      minHeight: 50,
      customshape: true,
      style: {
        width: "160",
        height: "160",
        display: "block",
        padding: "0px",
        margin: "0px",
        overflow: "show",
        color: "black",
        "background-color": "#FFFFFF",
        "border-color": "#333333",
        "border-width": "1px",
        "border-style": "solid",
        "border-radius": "0px",
        position: "absolute",
      },
      inner: {
        content: "",
        style: {
          display: "block",
          position: "absolute",
          width: "100%",
          height: "100%",
        },
      },
    },
    md: {
      edittable: false,
      resizable: true,
      droppable: true,
      customshape: true,
      style: {
        width: "460",
        height: "400",
        minHeight: "400px",
        display: "block",
        padding: "0px",
        margin: "0px",
        overflow: "show",
        color: "black",
        "background-color": "#FFFFFF",
        "border-color": "#333333",
        "border-width": "1px",
        "border-style": "solid",
        "border-radius": "0px",
        position: "absolute",
      },
      inner: {
        content: "",
        style: {
          display: "block",
          position: "absolute",
          width: "100%",
          height: "100%",
        },
      },
    },
    freehand: {
      edittable: false,
      resizable: false,
      droppable: false,
      defaultTip: "",
      customshape: false,
      style: {
        width: "160",
        height: "160",
        display: "flex",
        padding: "2px",
        margin: "0px",
        overflow: "show",
        "background-color": "transparent",
        "border-color": "#000000",
        "border-width": "0px",
        "border-style": "none",
        "border-radius": "0px",
        position: "absolute",
      },
      inner: {
        content: "",
        style: {
          display: "flex",
          padding: "0px",
          "font-size": "18px",
          color: "black",
          width: "100%",
          height: "100%",
          "z-index": 1,
          "justify-content": "flex-start",
          "align-items": "center",
        },
      },
    },
  },
  defaultSize: {
    yellowtip: {
      tip_arrow: { width: 60, height: 30 },
      tip_arrow2: { width: 60, height: 30 },
      tip_arrow3: { width: 30, height: 60 },
      tip_arrow4: { width: 30, height: 60 },
      tip_heart: { width: 50, height: 50 },
      tip_sig: { width: 60, height: 20 },
      tip_circle: { width: 50, height: 50 },
      tip_p5star: { width: 50, height: 50 },
      tip_p8star: { width: 50, height: 50 },
      tip_cubic: { width: 50, height: 50 },
      tip_clinder: { width: 50, height: 50 },
      tip_circle2: { width: 50, height: 50 },
      tip_check: { width: 50, height: 50 },
      tip_cross: { width: 50, height: 50 },
      tip_thunder: { width: 40, height: 50 },
      tip_smile: { width: 50, height: 50 },
      tip_circle3: { width: 50, height: 50 },
    },
    textblock: {
      default: { width: 240, height: 40 },
    },
    text: {
      default: { width: 30, height: 30 },
    },
    richtext: {
      default: { width: 400, height: 200 },
    },
    md: {
      default: { width: 460, height: 400 },
    },
  },
  layout: {
    spacing: {
      vert: 20,
      hori: 20,
    },
  },
  quickglance: {
    timer: 10,
  },
  morph: {
    delta: 2,
  },
  connect: {
    styles: {
      style1: {
        normal: {
          width: 2,
          color: "#4B92DB",
        },
        hover: {
          width: 4,
          color: "#4BDB92",
        },
      },
    },
  },
};

export default config;
